config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :lists do
    resources :todos
  end

  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'lists#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/list.rb
class List < ApplicationRecord
  include CableReady::Broadcaster
  after_save do
    cable_ready["lists"].inner_html(
      selector: "#lists",
      html: ApplicationController.renderer.render(partial: "lists/list", collection: List.order(position: :asc))
    )
    cable_ready.broadcast
  end

  has_many :todos, -> { order(position: :asc) }, dependent: :destroy

  acts_as_list

  validates :name, presence: true
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: [:show, :edit, :update, :destroy, :move]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.order(position: :asc)
    @list ||= List.new
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to root_path, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name, :position)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true, class: local_assigns[:class], data: local_assigns[:data]) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if list.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', list, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if list.persisted? %>
      <%= link_to "Cancel", list, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", lists_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<%= content_tag :div, id: dom_id(list), class: ["col-sm-3", dom_class(list)], data: { id: list.id } do %>
  <div class="card card-body bg-light">
    <h6><%= link_to list.name, list %></h6>

    <div data-controller="list" data-list-group="todos" data-id="<%= list.id %>">
      <% list.todos.each do |todo| %>
        <div class="card card-body mb-2" data-id="<%= todo.id %>">
          <%= todo.description %>
        </div>
      <% end %>
    </div>

    <div data-reflex-permanent data-controller="toggle" data-toggle-class="d-none">
      <%= link_to "Add todo", new_list_todo_path(list), data: { action: "click->toggle#toggle" }, class: "btn btn-light btn-block" %>
      <%= render "todos/form", todo: Todo.new, list: list, class: "d-none", data: { target: "toggle.toggleable" } %>
    </div>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<%= render 'form', list: @list %>

app/views/lists/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Lists</h1>
  </div>

  <div class="col-sm-6 text-right" data-controller="board" data-action="force:update@document->board#reload">
    <button class="btn btn-primary" data-action="click->board#reload">Reload Controller</button>
    <button class="btn btn-primary" data-reflex="click->ListReflex#reload">Reload No Controller</button>
    <%= link_to new_list_path, class: 'btn btn-primary' do %>
      Add New List
    <% end %>
  </div>
</div>

<div id="lists" class="row">
  <%= render partial: "list", collection: @lists %>
  <%= content_tag :div, class: ["col-sm-3"] do %>
    <div data-reflex-permanent data-controller="toggle" data-toggle-class="d-none">
      <%= link_to "Add List", new_list_path, data: { action: "click->toggle#toggle" }, class: "btn btn-light btn-block" %>
      <%= render "lists/form", list: List.new, class: "d-none", data: { target: "toggle.toggleable", action: "submit->board#create_list" } %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form', list: @list %>

app/views/lists/show.html.erb
<div class="page-header">
  <%= link_to lists_path, class: 'btn btn-default' do %>
    All Lists
  <% end %>
  <%= link_to edit_list_path(@list), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show list</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @list.name %></dd>

  <dt>Position:</dt>
  <dd><%= @list.position %></dd>

</dl>